type: object
properties:
  interval:
    $ref: ./enum/EnumApplicationIntervals.yaml
  indexer:
    $ref: ./Indexer.yaml
    description: Percentual que corresponde a mediana (taxa efetiva) cobrada do cliente
  customers:
    $ref: ./Customer.yaml
    description: Percentual de clientes em cada faixa.
required:
  - interval
  - indexer
  - customers
