type: object
descripion: Meta informações referente a API requisitada.
properties:
  totalRecords:
    type: integer
    description: Total de registros encontrados
    example: 1
  totalPages:
    type: integer
    description: Total de páginas para os registros encontrados
    example: 1
required:
  - totalRecords
  - totalPages
